# roles/hosts/tasks/main.yml
---

## - name: Install custom hosts file
##   template:
##     src: etc_hosts.j2
##     dest: "{{ hosts_file }}"
##     owner: root
##     group: root
##     mode: 0644
##     backup: "{{ host_file_backup }}"
##   tags: hosts

- name: Add Managed Block to {{ hosts_file }}
  blockinfile:
    path: "{{ hosts_file }}"
    owner: root
    group: root
    block: |
      {{ item.ip }} {{ item.name.split(".")[0] }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items: "{{ host_entries }}"
